export { SLink, SView } from './components';
export {
    route,
    routeChart,
    routeProps,
    routeStore,
    routeChartStore,
    push,
    replace,
    beforeEach,
    afterEach,
    setQuery,
    setParams,
    setRoutes,
    hash,
    host,
    hostname,
    origin,
    pathname,
    href,
    protocol,
    search,
} from './logic';
